# Component organisation
atoms:
- 'packages/components/atoms/**/*'

molecules:
- 'packages/components/molecules/**/*'

organisms:
- 'packages/components/organisms/**/*'

services:
- 'packages/services/**/*'

storybook:
- 'packages/storybook/**/*'

tools:
- 'packages/tools/**/*'
