export const SET_SUGGESTIONS = 'SET_SUGGESTIONS';
export const SET_ERRORS = 'SET_ERRORS';
export const SET_IS_VALID = 'SET_IS_VALID';
export const SET_IS_DIRTY = 'SET_IS_DIRTY';
export const SET_STREET_NUMBER_REQUIRED = 'SET_STREET_NUMBER_REQUIRED';
