language: node_js

node_js:
  - '10'
  - '8'

cache: yarn

sudo: false

script:
  - yarn danger ci

after_success:
  - yarn run test:cover:ci

notifications:
  email: false
  slack:
    secure: JZDN7aIRNEYShbq/EZ/QcydTjFb7xw68v39C/8XIaF4cs9BC/EVQFufpjTdYjLuqb5IqOUi0CRIhGADqUEiLWlNdRNQpadPKUtLZQj008QBpqnUiwooIz+H70YQX0OfZsLN8MtqkpQrzI9dKO8zQnjfLYYF7ihnk6jAMxMGYOcTQm/+MP/fV7hb8QZA17n1ThKV+TYttL6y31YqHN3HFqPm2FpfSHVgs8hHNo4Am4RpS9PX6E6jgWvK867xp8LERWYgDAo4RaEw1Cqudl+jwlVlznSDEQRSG5L6h7TZWJ0hnpL4ZITeFSmhEKlK4fJOgd6IFYH1EU8lRjWSLRh6Ii0SDfXdv+7ogHbCyhfusHgf2gdfT3a9HACjWv13lKlyPx1GD6k6e2FdKJ5TyqfLXz+E96mS/DuD5dLSukvJkyx3vN+v6jbZfSiskoXt031h8YaK68VGI0gSJS7a13P66DnkIyi0vmzqKGC43x1oDtpADfjnMXGCDsghRSm5++K/b95Kfl3XBK+G5Qvx9r0QsSLHXMccIdYmhe2s0RuD8fgbYilHyDNnOzWgjiytlfIyVMcRziuz/KUWn4oAvsT3bIjs+wZJhC5AVDMiTj8V4QFU1cdOCgyQJhE5Vtye5DTfKCBfABrS4i9IP8FYF9PBWWr2b4WEMFl1BKvzq3AQvaFk=
