nodeLinker: node-modules

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: "@yarnpkg/plugin-interactive-tools"
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: "@yarnpkg/plugin-workspace-tools"

packageExtensions:
    "@justeat/f-button@*":
        peerDependencies:
            "@vue/cli-service": "*"
            "@vue/cli-plugin-unit-jest": "*"
            "@samhammer/vue-cli-plugin-stylelint": "*"


yarnPath: .yarn/releases/yarn-3.1.1.cjs


# @justeat/f-button@workspace:packages/components/atoms/f-button doesn't provide stylelint (p92631), requested by @samhammer/vue-cli-plugin-stylelint
# ➤ YN0002: │ @justeat/f-button@workspace:packages/components/atoms/f-button doesn't provide vue-template-compiler (p3108e), requested by @vue/test-utils
# ➤ YN0002: │ @justeat/f-button@workspace:packages/components/atoms/f-button [89ff3] doesn't provide stylelint (pe72ec), requested by @samhammer/vue-cli-plugin-stylelint
# ➤ YN0002: │ @justeat/f-button@workspace:packages/components/atoms/f-button [89ff3] doesn't provide vue-template-compiler (p19939), requested by @vue/test-utils
# ➤ YN0002: │ @justeat/f-button@workspace:packages/components/atoms/f-button [e43a8] doesn't provide stylelint (p27028), requested by @samhammer/vue-cli-plugin-stylelint
# ➤ YN0002: │ @justeat/f-button@workspace:packages/components/atoms/f-button [e43a8] doesn't provide vue-template-compiler (p3ee38), requested by @vue/test-utils
