/* eslint-disable import/prefer-default-export */
const IS_BATCH_PUBLISHING_ENABLED = true;
const BATCH_QUEUE_SIZE = 5;
const BATCH_QUEUE_MAX_BYTES = 1000;
const BATCH_INTERVAL_TIMER = 3000;

export {
    IS_BATCH_PUBLISHING_ENABLED,
    BATCH_QUEUE_SIZE,
    BATCH_INTERVAL_TIMER,
    BATCH_QUEUE_MAX_BYTES
};
