# version: 2.1 # use CircleCI 2.1
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2.1

commands:
  install_node_dependencies:
    description: Installs the node dependencies
    steps:
      - run: yarn install

  build_packages:
    description: Locally builds all packages in the monorepo
    steps:
      - run: # Check UI packages all build as expected
          name: Build Packages
          command: yarn build

executors:
  node:
    docker:
      # specify the version you desire here
      - image: circleci/node:12.21-browsers # For latest available images check – https://circleci.com/docs/2.0/docker-image-tags.json

jobs:

  working_directory: ~/repo
  
  local:
    executor: node
    environment:
      # required to prevent ENOMEM errors
      LERNA_ARGS: --concurrency 1
    steps: # a collection of executable commands
      - checkout # special step to check out source code to working directory
      - install_node_dependencies
      - build_packages
      - run: # Lint packages
          name: Run Lint Tasks on Packages
          command: yarn lint
      - run: # Run Tests
          name: Run Unit / Integration Tests
          command: yarn test
      - run: # Install Component Test Dependencies
          name: Install Component Test Dependencies
          command: yarn global add @vue/cli @vue/cli-service-global
      - run: # Build Storybook
          name: Build Storybook
          command: yarn storybook:build
      - run: # Serve Storybook
          name: Serve Storybook
          command: yarn storybook:serve-static
          background: true
      - run: # Run Component UI Tests
          name: Run WebDriverIO Component Tests
          command: yarn test-component:chrome
      - run: # Run Accessibility UI Tests
          name: Run WebDriverIO Accessibility Tests
          command: yarn test-a11y:chrome

workflows:
  version: 2

  local:
    jobs:
      - local:
          context: web-core
          filters:
            branches:
              ignore: 'gh-pages'