export const GEO_UNKNOWN_ERROR = 'GEO_UNKNOWN_ERROR';
export const GEO_PERMISSION_DENIED = 'GEO_PERMISSION_DENIED';
export const GEO_POSITION_UNAVAILABLE = 'GEO_POSITION_UNAVAILABLE';
export const GEO_UNAVAILABLE = 'GEO_UNAVAILABLE';
export const GEO_TIMEOUT = 'GEO_TIMEOUT';
export const GEO_ERROR = 'GEO_ERROR';

export const NO_SUGGESTION_FOUND = 'NO_SUGGESTION_FOUND';
export const SEARCH_ERROR = 'SEARCH_ERROR';
export const SERVICE_UNAVAILABLE = 'SERVICE_UNAVAILABLE';

