export const CHECKOUT_METHOD_COLLECTION = 'Collection';
export const CHECKOUT_METHOD_DELIVERY = 'Delivery';

export const VALID_CHECKOUT_METHOD = [CHECKOUT_METHOD_COLLECTION, CHECKOUT_METHOD_DELIVERY];
