export const UPDATE_AUTH = 'UPDATE_AUTH';
export const UPDATE_AVAILABLE_FULFILMENT_TIMES = 'UPDATE_AVAILABLE_FULFILMENT_TIMES';
export const UPDATE_BASKET_DETAILS = 'UPDATE_BASKET_DETAILS';
export const UPDATE_CUSTOMER_DETAILS = 'UPDATE_CUSTOMER_DETAILS';
export const UPDATE_FULFILMENT_ADDRESS = 'UPDATE_FULFILMENT_ADDRESS';
export const UPDATE_FULFILMENT_TIME = 'UPDATE_FULFILMENT_TIME';
export const UPDATE_STATE = 'UPDATE_STATE';
