// Checkout module
export const CLEAR_DOB_ERROR = 'CLEAR_DOB_ERROR';
export const UPDATE_ADDRESS = 'UPDATE_LOCAL_STORAGE_ADDRESS';
export const UPDATE_AUTH = 'UPDATE_AUTH';
export const UPDATE_AUTH_GUEST = 'UPDATE_AUTH_GUEST';
export const UPDATE_AVAILABLE_FULFILMENT_TIMES = 'UPDATE_AVAILABLE_FULFILMENT_TIMES';
export const UPDATE_BASKET_DETAILS = 'UPDATE_BASKET_DETAILS';
export const UPDATE_CUSTOMER_DETAILS = 'UPDATE_CUSTOMER_DETAILS';
export const UPDATE_DATE_OF_BIRTH = 'UPDATE_DATE_OF_BIRTH';
export const UPDATE_ERRORS = 'UPDATE_ERRORS';
export const UPDATE_FULFILMENT_ADDRESS = 'UPDATE_FULFILMENT_ADDRESS';
export const UPDATE_FULFILMENT_TIME = 'UPDATE_FULFILMENT_TIME';
export const UPDATE_GEO_LOCATION = 'UPDATE_GEO_LOCATION';
export const UPDATE_HAS_ASAP_SELECTED = 'UPDATE_HAS_ASAP_SELECTED';
export const UPDATE_IS_FULFILLABLE = 'UPDATE_IS_FULFILLABLE';
export const UPDATE_MESSAGE = 'UPDATE_MESSAGE';
export const UPDATE_ORDER_PLACED = 'UPDATE_ORDER_PLACED';
export const UPDATE_PHONE_NUMBER = 'UPDATE_PHONE_NUMBER';
export const UPDATE_STATE = 'UPDATE_STATE';
export const UPDATE_TABLE_IDENTIFIER = 'UPDATE_TABLE_IDENTIFIER';
export const UPDATE_USER_NOTE = 'UPDATE_USER_NOTE';

// Analytics module
export const UPDATE_AUTOFILL = 'UPDATE_AUTOFILL';
export const UPDATE_CHANGED_FIELD = 'UPDATE_CHANGED_FIELD';

// Experimentation module
export const UPDATE_EXPERIMENTS_STATE = 'UPDATE_EXPERIMENTS_STATE';
