#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

BRANCH_NAME=$(git branch | grep '*' | sed 's/* //')

# if we're rebasing, don't run
if [ $BRANCH_NAME != '(no branch)' ]
then
  # your regularly scheduled hooks
  yarn lint --since HEAD
  yarn test --since HEAD

  exec < /dev/tty && node_modules/.bin/git-cz --hook || true
fi
