name: "Pull Request Labeler"
on:
- pull_request_target

jobs:
  wip:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/labeler@v3
      with:
        configuration-path: '.github/wip-labeler.yml'
        repo-token: "${{ secrets.GITHUB_TOKEN }}"

  triage:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/labeler@v3
      with:
        configuration-path: '.github/component-labeler.yml'
        repo-token: "${{ secrets.GITHUB_TOKEN }}"
        sync-labels: true
