export const ADD_TO_PUBLISH_QUEUE = 'ADD_TO_PUBLISH_QUEUE';
export const CLEAR_PUBLISH_QUEUE = 'CLEAR_PUBLISH_QUEUE';
export const SET_INTERVAL_TIMER = 'SET_INTERVAL_TIMER';
export const CLEAR_INTERVAL_TIMER = 'CLEAR_INTERVAL_TIMER';

